### ISSUE TITLE
Version number still shows as 2.015

### ISSUE THREAD

**Issue by domisjustanumber** [leadedge/SpoutCam#6]
I just downloaded the latest release (2.030 from https://github.com/leadedge/SpoutCam/releases/tag/2.030)

The SpoutSettings UI still says version 2.015

Is the bundle the right file and this is just a bit of old text that needs updating?

![image](https://github.com/leadedge/SpoutCam/assets/36455793/62617d61-504d-4b56-9cbc-4ee5b57bf8db)

**Comment by leadedge** [comment]
The latest version is 2.015. After the last SpoutCam release 2.090, there was an issue with permissions and it was a quick fix to elevate to _requiring_ permissions instead of using the highest available so I updated the 2.090 download straight away. 

Windows UAC will probably complain, but the program has to start with Administrator permissions so that the Directshow filters can be registered.

The latest version was  rebuilt yesterday with up to date Spout SDK files . I checked the file in the download and it is the correct one.
